### ISSUE TITLE
The sample app dosn't handle client error not found

### ISSUE THREAD

**Issue by Makuna** [smeshlink/CoAP.NET#16]
If the sever returns client error not found, the client should not continue to request the resource.

**Comment by longshine** [comment]
I'm not quite sure what the issue is here.
The transmission of a message will be cleaned up if an expecting response is arrived.
Since the (4.04) is a valid response, the client will NOT retransmit previous request message.
I have tried Example/CoAP.Client on other CoAP servers, and it worked just as above.

Demo request and response:

<pre>
==[ COAP Request ]============================================
ID     : -1
Type   : CON
Token  :
Method : GET
Dest   : 127.0.0.1:5683
Options: URI-Path=neverland, Content-Type=text/plain
Payload: 0 Bytes
==============================================================
</pre>

<pre>
==[ COAP Response ]============================================
ID     : 64184
Type   : ACK
Token  : 686935F3
Status : 4.04 Not Found
Source : 127.0.0.1:5683
Options:
Payload: 0 Bytes
===============================================================
</pre>

Would you please give some more details?

**Comment by Makuna** [comment]
Problem found.  The server was sending packets with corrupted first bytes, which would always set version to zero and effect other properties in a consistent fashion. 

So, the only real problem is that the client is not checking the version number.

**Comment by longshine** [comment]
Yes, the version bits are not checked now.
I find some lines in the RFC:

> Version (Ver):  2-bit unsigned integer. Indicates the CoAP version number.
> ...
> Messages with unknown version numbers MUST be silently ignored.

This will be fixed in the future. Thanks~
