### ISSUE TITLE
Coap.Net

### ISSUE THREAD

**Issue by Shriyanshmit** [smeshlink/CoAP.NET#26]
Hi,
Please let me know how we can send the token to  COAP server and how we can define message type (CON, NON, ACK, RST) when we send client request to COAP server.

Thanks

**Comment by longshine** [comment]
Hi~

About token:
Token is defined as a property in `Message` class:
```csharp
byte[] Message.Token { get; set }
```
It is an array of bytes, with 0 - 8 bytes.
If not set, the `TokenLayer` inside will generate a token for each request.

```csharp
Request request;

request.Token = new byte[] { 0xab, 0xcd };
```

About message type:
It is not recommended to define the message type of requests directly,
because normally a request can only be CON or NON.
To specify CON/NON to a request, use this constructor:
`Request(Method method, Boolean confirmable)`
while the second param indicates whether this request is CON or not.
`true` for CON, `false` for NON. The default value is `true`.

If you really want to set the message type manually, please refer to the
`Type` property in `Message` class:
```csharp
MessageType Message.Type { get; set; }
```
