### ISSUE TITLE
Unable to send acknowledgement from CoAP server to CoAP client

### ISSUE THREAD

**Issue by manishi2V** [smeshlink/CoAP.NET#59]
I am using following code:

server.FindEndPoint(5683).ReceivingRequest += new EventHandler<MessageEventArgs<Request>>(ExampleServer_ReceivingRequest);

I am able to receive client request by this method and want to send a custom acknowledgement.

I am expecting acknowledgement in the client side by this method
client.Respond += new EventHandler<ResponseEventArgs>(client_Respond);

Please suggest me, how do I execute above issue.

**Comment by longshine** [comment]
Hi,

You **cannot** directly send a request (or response) message to a client, since it will drop all unexpected messages silently.

Actually, there is no need to send additional ACK because each CON request from client will be acknowledged while a response is sent. (see CoAP [2.1 Messaging Model](https://tools.ietf.org/html/rfc7252#section-2.1) and [2.2 Request/Response Model](https://tools.ietf.org/html/rfc7252#section-2.2)).

If you want to send separate ACK later please take a look at the **piggybacked response**.
